#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.UI.Mvc3.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_SMS")]
	public partial class SMSDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_BorrowGood(tb_BorrowGood instance);
    partial void Updatetb_BorrowGood(tb_BorrowGood instance);
    partial void Deletetb_BorrowGood(tb_BorrowGood instance);
    partial void Inserttb_User(tb_User instance);
    partial void Updatetb_User(tb_User instance);
    partial void Deletetb_User(tb_User instance);
    partial void Inserttb_Check(tb_Check instance);
    partial void Updatetb_Check(tb_Check instance);
    partial void Deletetb_Check(tb_Check instance);
    partial void Inserttb_InStore(tb_InStore instance);
    partial void Updatetb_InStore(tb_InStore instance);
    partial void Deletetb_InStore(tb_InStore instance);
    partial void Inserttb_OutStore(tb_OutStore instance);
    partial void Updatetb_OutStore(tb_OutStore instance);
    partial void Deletetb_OutStore(tb_OutStore instance);
    partial void Inserttb_Provider(tb_Provider instance);
    partial void Updatetb_Provider(tb_Provider instance);
    partial void Deletetb_Provider(tb_Provider instance);
    partial void Inserttb_ReturnGood(tb_ReturnGood instance);
    partial void Updatetb_ReturnGood(tb_ReturnGood instance);
    partial void Deletetb_ReturnGood(tb_ReturnGood instance);
    partial void Inserttb_Storage(tb_Storage instance);
    partial void Updatetb_Storage(tb_Storage instance);
    partial void Deletetb_Storage(tb_Storage instance);
    #endregion
		
		public SMSDataClassesDataContext() :
        base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SMSDbConnString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SMSDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMSDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMSDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMSDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_BorrowGood> tb_BorrowGoods
		{
			get
			{
				return this.GetTable<tb_BorrowGood>();
			}
		}
		
		public System.Data.Linq.Table<tb_User> tb_Users
		{
			get
			{
				return this.GetTable<tb_User>();
			}
		}
		
		public System.Data.Linq.Table<tb_Check> tb_Checks
		{
			get
			{
				return this.GetTable<tb_Check>();
			}
		}
		
		public System.Data.Linq.Table<tb_GoodsInfo> tb_GoodsInfos
		{
			get
			{
				return this.GetTable<tb_GoodsInfo>();
			}
		}
		
		public System.Data.Linq.Table<tb_InStore> tb_InStores
		{
			get
			{
				return this.GetTable<tb_InStore>();
			}
		}
		
		public System.Data.Linq.Table<tb_OutStore> tb_OutStores
		{
			get
			{
				return this.GetTable<tb_OutStore>();
			}
		}
		
		public System.Data.Linq.Table<tb_Provider> tb_Providers
		{
			get
			{
				return this.GetTable<tb_Provider>();
			}
		}
		
		public System.Data.Linq.Table<tb_ReturnGood> tb_ReturnGoods
		{
			get
			{
				return this.GetTable<tb_ReturnGood>();
			}
		}
		
		public System.Data.Linq.Table<tb_Storage> tb_Storages
		{
			get
			{
				return this.GetTable<tb_Storage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_BorrowGoods")]
	public partial class tb_BorrowGood : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _BGID;
		
		private string _GoodsName;
		
		private string _StoreName;
		
		private string _GoodsSpec;
		
		private System.Nullable<long> _GoodsNum;
		
		private System.Nullable<System.DateTime> _BGDate;
		
		private string _HandlePeople;
		
		private string _BGPeople;
		
		private string _BGUnit;
		
		private string _BGRemark;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBGIDChanging(long value);
    partial void OnBGIDChanged();
    partial void OnGoodsNameChanging(string value);
    partial void OnGoodsNameChanged();
    partial void OnStoreNameChanging(string value);
    partial void OnStoreNameChanged();
    partial void OnGoodsSpecChanging(string value);
    partial void OnGoodsSpecChanged();
    partial void OnGoodsNumChanging(System.Nullable<long> value);
    partial void OnGoodsNumChanged();
    partial void OnBGDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBGDateChanged();
    partial void OnHandlePeopleChanging(string value);
    partial void OnHandlePeopleChanged();
    partial void OnBGPeopleChanging(string value);
    partial void OnBGPeopleChanged();
    partial void OnBGUnitChanging(string value);
    partial void OnBGUnitChanged();
    partial void OnBGRemarkChanging(string value);
    partial void OnBGRemarkChanged();
    #endregion
		
		public tb_BorrowGood()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BGID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long BGID
		{
			get
			{
				return this._BGID;
			}
			set
			{
				if ((this._BGID != value))
				{
					this.OnBGIDChanging(value);
					this.SendPropertyChanging();
					this._BGID = value;
					this.SendPropertyChanged("BGID");
					this.OnBGIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsName", DbType="VarChar(50)")]
		public string GoodsName
		{
			get
			{
				return this._GoodsName;
			}
			set
			{
				if ((this._GoodsName != value))
				{
					this.OnGoodsNameChanging(value);
					this.SendPropertyChanging();
					this._GoodsName = value;
					this.SendPropertyChanged("GoodsName");
					this.OnGoodsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreName", DbType="VarChar(100)")]
		public string StoreName
		{
			get
			{
				return this._StoreName;
			}
			set
			{
				if ((this._StoreName != value))
				{
					this.OnStoreNameChanging(value);
					this.SendPropertyChanging();
					this._StoreName = value;
					this.SendPropertyChanged("StoreName");
					this.OnStoreNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsSpec", DbType="VarChar(50)")]
		public string GoodsSpec
		{
			get
			{
				return this._GoodsSpec;
			}
			set
			{
				if ((this._GoodsSpec != value))
				{
					this.OnGoodsSpecChanging(value);
					this.SendPropertyChanging();
					this._GoodsSpec = value;
					this.SendPropertyChanged("GoodsSpec");
					this.OnGoodsSpecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsNum", DbType="BigInt")]
		public System.Nullable<long> GoodsNum
		{
			get
			{
				return this._GoodsNum;
			}
			set
			{
				if ((this._GoodsNum != value))
				{
					this.OnGoodsNumChanging(value);
					this.SendPropertyChanging();
					this._GoodsNum = value;
					this.SendPropertyChanged("GoodsNum");
					this.OnGoodsNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BGDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BGDate
		{
			get
			{
				return this._BGDate;
			}
			set
			{
				if ((this._BGDate != value))
				{
					this.OnBGDateChanging(value);
					this.SendPropertyChanging();
					this._BGDate = value;
					this.SendPropertyChanged("BGDate");
					this.OnBGDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HandlePeople", DbType="VarChar(20)")]
		public string HandlePeople
		{
			get
			{
				return this._HandlePeople;
			}
			set
			{
				if ((this._HandlePeople != value))
				{
					this.OnHandlePeopleChanging(value);
					this.SendPropertyChanging();
					this._HandlePeople = value;
					this.SendPropertyChanged("HandlePeople");
					this.OnHandlePeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BGPeople", DbType="VarChar(20)")]
		public string BGPeople
		{
			get
			{
				return this._BGPeople;
			}
			set
			{
				if ((this._BGPeople != value))
				{
					this.OnBGPeopleChanging(value);
					this.SendPropertyChanging();
					this._BGPeople = value;
					this.SendPropertyChanged("BGPeople");
					this.OnBGPeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BGUnit", DbType="VarChar(100)")]
		public string BGUnit
		{
			get
			{
				return this._BGUnit;
			}
			set
			{
				if ((this._BGUnit != value))
				{
					this.OnBGUnitChanging(value);
					this.SendPropertyChanging();
					this._BGUnit = value;
					this.SendPropertyChanged("BGUnit");
					this.OnBGUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BGRemark", DbType="VarChar(1000)")]
		public string BGRemark
		{
			get
			{
				return this._BGRemark;
			}
			set
			{
				if ((this._BGRemark != value))
				{
					this.OnBGRemarkChanging(value);
					this.SendPropertyChanging();
					this._BGRemark = value;
					this.SendPropertyChanged("BGRemark");
					this.OnBGRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_User")]
	public partial class tb_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _UserID;
		
		private string _UserName;
		
		private string _UserPwd;
		
		private string _UserRight;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(long value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnUserPwdChanging(string value);
    partial void OnUserPwdChanged();
    partial void OnUserRightChanging(string value);
    partial void OnUserRightChanged();
    #endregion
		
		public tb_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(20)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPwd", DbType="VarChar(20)")]
		public string UserPwd
		{
			get
			{
				return this._UserPwd;
			}
			set
			{
				if ((this._UserPwd != value))
				{
					this.OnUserPwdChanging(value);
					this.SendPropertyChanging();
					this._UserPwd = value;
					this.SendPropertyChanged("UserPwd");
					this.OnUserPwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRight", DbType="Char(10)")]
		public string UserRight
		{
			get
			{
				return this._UserRight;
			}
			set
			{
				if ((this._UserRight != value))
				{
					this.OnUserRightChanging(value);
					this.SendPropertyChanging();
					this._UserRight = value;
					this.SendPropertyChanged("UserRight");
					this.OnUserRightChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Check")]
	public partial class tb_Check : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _CheckID;
		
		private System.Nullable<long> _GoodsID;
		
		private string _StoreName;
		
		private string _GoodsName;
		
		private string _GoodsUnit;
		
		private System.Nullable<long> _CheckNum;
		
		private System.Nullable<long> _PALNum;
		
		private System.Nullable<System.DateTime> _CheckDate;
		
		private string _CheckPeople;
		
		private string _CheckRemark;
		
		private string _Editer;
		
		private System.Nullable<System.DateTime> _EditDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCheckIDChanging(long value);
    partial void OnCheckIDChanged();
    partial void OnGoodsIDChanging(System.Nullable<long> value);
    partial void OnGoodsIDChanged();
    partial void OnStoreNameChanging(string value);
    partial void OnStoreNameChanged();
    partial void OnGoodsNameChanging(string value);
    partial void OnGoodsNameChanged();
    partial void OnGoodsUnitChanging(string value);
    partial void OnGoodsUnitChanged();
    partial void OnCheckNumChanging(System.Nullable<long> value);
    partial void OnCheckNumChanged();
    partial void OnPALNumChanging(System.Nullable<long> value);
    partial void OnPALNumChanged();
    partial void OnCheckDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCheckDateChanged();
    partial void OnCheckPeopleChanging(string value);
    partial void OnCheckPeopleChanged();
    partial void OnCheckRemarkChanging(string value);
    partial void OnCheckRemarkChanged();
    partial void OnEditerChanging(string value);
    partial void OnEditerChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    #endregion
		
		public tb_Check()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long CheckID
		{
			get
			{
				return this._CheckID;
			}
			set
			{
				if ((this._CheckID != value))
				{
					this.OnCheckIDChanging(value);
					this.SendPropertyChanging();
					this._CheckID = value;
					this.SendPropertyChanged("CheckID");
					this.OnCheckIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsID", DbType="BigInt")]
		public System.Nullable<long> GoodsID
		{
			get
			{
				return this._GoodsID;
			}
			set
			{
				if ((this._GoodsID != value))
				{
					this.OnGoodsIDChanging(value);
					this.SendPropertyChanging();
					this._GoodsID = value;
					this.SendPropertyChanged("GoodsID");
					this.OnGoodsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreName", DbType="VarChar(100)")]
		public string StoreName
		{
			get
			{
				return this._StoreName;
			}
			set
			{
				if ((this._StoreName != value))
				{
					this.OnStoreNameChanging(value);
					this.SendPropertyChanging();
					this._StoreName = value;
					this.SendPropertyChanged("StoreName");
					this.OnStoreNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsName", DbType="VarChar(50)")]
		public string GoodsName
		{
			get
			{
				return this._GoodsName;
			}
			set
			{
				if ((this._GoodsName != value))
				{
					this.OnGoodsNameChanging(value);
					this.SendPropertyChanging();
					this._GoodsName = value;
					this.SendPropertyChanged("GoodsName");
					this.OnGoodsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsUnit", DbType="Char(8)")]
		public string GoodsUnit
		{
			get
			{
				return this._GoodsUnit;
			}
			set
			{
				if ((this._GoodsUnit != value))
				{
					this.OnGoodsUnitChanging(value);
					this.SendPropertyChanging();
					this._GoodsUnit = value;
					this.SendPropertyChanged("GoodsUnit");
					this.OnGoodsUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckNum", DbType="BigInt")]
		public System.Nullable<long> CheckNum
		{
			get
			{
				return this._CheckNum;
			}
			set
			{
				if ((this._CheckNum != value))
				{
					this.OnCheckNumChanging(value);
					this.SendPropertyChanging();
					this._CheckNum = value;
					this.SendPropertyChanged("CheckNum");
					this.OnCheckNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PALNum", DbType="BigInt")]
		public System.Nullable<long> PALNum
		{
			get
			{
				return this._PALNum;
			}
			set
			{
				if ((this._PALNum != value))
				{
					this.OnPALNumChanging(value);
					this.SendPropertyChanging();
					this._PALNum = value;
					this.SendPropertyChanged("PALNum");
					this.OnPALNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CheckDate
		{
			get
			{
				return this._CheckDate;
			}
			set
			{
				if ((this._CheckDate != value))
				{
					this.OnCheckDateChanging(value);
					this.SendPropertyChanging();
					this._CheckDate = value;
					this.SendPropertyChanged("CheckDate");
					this.OnCheckDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckPeople", DbType="VarChar(20)")]
		public string CheckPeople
		{
			get
			{
				return this._CheckPeople;
			}
			set
			{
				if ((this._CheckPeople != value))
				{
					this.OnCheckPeopleChanging(value);
					this.SendPropertyChanging();
					this._CheckPeople = value;
					this.SendPropertyChanged("CheckPeople");
					this.OnCheckPeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckRemark", DbType="VarChar(1000)")]
		public string CheckRemark
		{
			get
			{
				return this._CheckRemark;
			}
			set
			{
				if ((this._CheckRemark != value))
				{
					this.OnCheckRemarkChanging(value);
					this.SendPropertyChanging();
					this._CheckRemark = value;
					this.SendPropertyChanged("CheckRemark");
					this.OnCheckRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editer", DbType="VarChar(20)")]
		public string Editer
		{
			get
			{
				return this._Editer;
			}
			set
			{
				if ((this._Editer != value))
				{
					this.OnEditerChanging(value);
					this.SendPropertyChanging();
					this._Editer = value;
					this.SendPropertyChanged("Editer");
					this.OnEditerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_GoodsInfo")]
	public partial class tb_GoodsInfo
	{
		
		private long _GoodsID;
		
		private string _GoodsName;
		
		private string _StoreName;
		
		private string _GoodsSpec;
		
		private string _GoodsUnit;
		
		private System.Nullable<long> _GoodsNum;
		
		private System.Nullable<decimal> _GoodsInPrice;
		
		private System.Nullable<decimal> _GoodsOutPrice;
		
		private System.Nullable<long> _GoodsLeast;
		
		private System.Nullable<long> _GoodsMost;
		
		private string _Editer;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		public tb_GoodsInfo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsID", DbType="BigInt NOT NULL")]
		public long GoodsID
		{
			get
			{
				return this._GoodsID;
			}
			set
			{
				if ((this._GoodsID != value))
				{
					this._GoodsID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsName", DbType="VarChar(50)")]
		public string GoodsName
		{
			get
			{
				return this._GoodsName;
			}
			set
			{
				if ((this._GoodsName != value))
				{
					this._GoodsName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreName", DbType="VarChar(100)")]
		public string StoreName
		{
			get
			{
				return this._StoreName;
			}
			set
			{
				if ((this._StoreName != value))
				{
					this._StoreName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsSpec", DbType="VarChar(50)")]
		public string GoodsSpec
		{
			get
			{
				return this._GoodsSpec;
			}
			set
			{
				if ((this._GoodsSpec != value))
				{
					this._GoodsSpec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsUnit", DbType="Char(8)")]
		public string GoodsUnit
		{
			get
			{
				return this._GoodsUnit;
			}
			set
			{
				if ((this._GoodsUnit != value))
				{
					this._GoodsUnit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsNum", DbType="BigInt")]
		public System.Nullable<long> GoodsNum
		{
			get
			{
				return this._GoodsNum;
			}
			set
			{
				if ((this._GoodsNum != value))
				{
					this._GoodsNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsInPrice", DbType="Money")]
		public System.Nullable<decimal> GoodsInPrice
		{
			get
			{
				return this._GoodsInPrice;
			}
			set
			{
				if ((this._GoodsInPrice != value))
				{
					this._GoodsInPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsOutPrice", DbType="Money")]
		public System.Nullable<decimal> GoodsOutPrice
		{
			get
			{
				return this._GoodsOutPrice;
			}
			set
			{
				if ((this._GoodsOutPrice != value))
				{
					this._GoodsOutPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsLeast", DbType="BigInt")]
		public System.Nullable<long> GoodsLeast
		{
			get
			{
				return this._GoodsLeast;
			}
			set
			{
				if ((this._GoodsLeast != value))
				{
					this._GoodsLeast = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsMost", DbType="BigInt")]
		public System.Nullable<long> GoodsMost
		{
			get
			{
				return this._GoodsMost;
			}
			set
			{
				if ((this._GoodsMost != value))
				{
					this._GoodsMost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editer", DbType="VarChar(20)")]
		public string Editer
		{
			get
			{
				return this._Editer;
			}
			set
			{
				if ((this._Editer != value))
				{
					this._Editer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this._EditDate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_InStore")]
	public partial class tb_InStore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ISID;
		
		private System.Nullable<long> _GoodsID;
		
		private string _GoodsName;
		
		private string _PrName;
		
		private string _StoreName;
		
		private string _GoodsSpec;
		
		private string _GoodsUnit;
		
		private System.Nullable<long> _GoodsNum;
		
		private System.Nullable<decimal> _GoodsPrice;
		
		private System.Nullable<decimal> _GoodsAPrice;
		
		private System.Nullable<System.DateTime> _ISDate;
		
		private string _HandlePeople;
		
		private string _ISRemark;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnISIDChanging(long value);
    partial void OnISIDChanged();
    partial void OnGoodsIDChanging(System.Nullable<long> value);
    partial void OnGoodsIDChanged();
    partial void OnGoodsNameChanging(string value);
    partial void OnGoodsNameChanged();
    partial void OnPrNameChanging(string value);
    partial void OnPrNameChanged();
    partial void OnStoreNameChanging(string value);
    partial void OnStoreNameChanged();
    partial void OnGoodsSpecChanging(string value);
    partial void OnGoodsSpecChanged();
    partial void OnGoodsUnitChanging(string value);
    partial void OnGoodsUnitChanged();
    partial void OnGoodsNumChanging(System.Nullable<long> value);
    partial void OnGoodsNumChanged();
    partial void OnGoodsPriceChanging(System.Nullable<decimal> value);
    partial void OnGoodsPriceChanged();
    partial void OnGoodsAPriceChanging(System.Nullable<decimal> value);
    partial void OnGoodsAPriceChanged();
    partial void OnISDateChanging(System.Nullable<System.DateTime> value);
    partial void OnISDateChanged();
    partial void OnHandlePeopleChanging(string value);
    partial void OnHandlePeopleChanged();
    partial void OnISRemarkChanging(string value);
    partial void OnISRemarkChanged();
    #endregion
		
		public tb_InStore()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ISID
		{
			get
			{
				return this._ISID;
			}
			set
			{
				if ((this._ISID != value))
				{
					this.OnISIDChanging(value);
					this.SendPropertyChanging();
					this._ISID = value;
					this.SendPropertyChanged("ISID");
					this.OnISIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsID", DbType="BigInt")]
		public System.Nullable<long> GoodsID
		{
			get
			{
				return this._GoodsID;
			}
			set
			{
				if ((this._GoodsID != value))
				{
					this.OnGoodsIDChanging(value);
					this.SendPropertyChanging();
					this._GoodsID = value;
					this.SendPropertyChanged("GoodsID");
					this.OnGoodsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsName", DbType="VarChar(50)")]
		public string GoodsName
		{
			get
			{
				return this._GoodsName;
			}
			set
			{
				if ((this._GoodsName != value))
				{
					this.OnGoodsNameChanging(value);
					this.SendPropertyChanging();
					this._GoodsName = value;
					this.SendPropertyChanged("GoodsName");
					this.OnGoodsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrName", DbType="VarChar(100)")]
		public string PrName
		{
			get
			{
				return this._PrName;
			}
			set
			{
				if ((this._PrName != value))
				{
					this.OnPrNameChanging(value);
					this.SendPropertyChanging();
					this._PrName = value;
					this.SendPropertyChanged("PrName");
					this.OnPrNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreName", DbType="VarChar(100)")]
		public string StoreName
		{
			get
			{
				return this._StoreName;
			}
			set
			{
				if ((this._StoreName != value))
				{
					this.OnStoreNameChanging(value);
					this.SendPropertyChanging();
					this._StoreName = value;
					this.SendPropertyChanged("StoreName");
					this.OnStoreNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsSpec", DbType="VarChar(50)")]
		public string GoodsSpec
		{
			get
			{
				return this._GoodsSpec;
			}
			set
			{
				if ((this._GoodsSpec != value))
				{
					this.OnGoodsSpecChanging(value);
					this.SendPropertyChanging();
					this._GoodsSpec = value;
					this.SendPropertyChanged("GoodsSpec");
					this.OnGoodsSpecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsUnit", DbType="Char(8)")]
		public string GoodsUnit
		{
			get
			{
				return this._GoodsUnit;
			}
			set
			{
				if ((this._GoodsUnit != value))
				{
					this.OnGoodsUnitChanging(value);
					this.SendPropertyChanging();
					this._GoodsUnit = value;
					this.SendPropertyChanged("GoodsUnit");
					this.OnGoodsUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsNum", DbType="BigInt")]
		public System.Nullable<long> GoodsNum
		{
			get
			{
				return this._GoodsNum;
			}
			set
			{
				if ((this._GoodsNum != value))
				{
					this.OnGoodsNumChanging(value);
					this.SendPropertyChanging();
					this._GoodsNum = value;
					this.SendPropertyChanged("GoodsNum");
					this.OnGoodsNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsPrice", DbType="Money")]
		public System.Nullable<decimal> GoodsPrice
		{
			get
			{
				return this._GoodsPrice;
			}
			set
			{
				if ((this._GoodsPrice != value))
				{
					this.OnGoodsPriceChanging(value);
					this.SendPropertyChanging();
					this._GoodsPrice = value;
					this.SendPropertyChanged("GoodsPrice");
					this.OnGoodsPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsAPrice", AutoSync=AutoSync.Always, DbType="Money", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> GoodsAPrice
		{
			get
			{
				return this._GoodsAPrice;
			}
			set
			{
				if ((this._GoodsAPrice != value))
				{
					this.OnGoodsAPriceChanging(value);
					this.SendPropertyChanging();
					this._GoodsAPrice = value;
					this.SendPropertyChanged("GoodsAPrice");
					this.OnGoodsAPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ISDate
		{
			get
			{
				return this._ISDate;
			}
			set
			{
				if ((this._ISDate != value))
				{
					this.OnISDateChanging(value);
					this.SendPropertyChanging();
					this._ISDate = value;
					this.SendPropertyChanged("ISDate");
					this.OnISDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HandlePeople", DbType="VarChar(20)")]
		public string HandlePeople
		{
			get
			{
				return this._HandlePeople;
			}
			set
			{
				if ((this._HandlePeople != value))
				{
					this.OnHandlePeopleChanging(value);
					this.SendPropertyChanging();
					this._HandlePeople = value;
					this.SendPropertyChanged("HandlePeople");
					this.OnHandlePeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISRemark", DbType="VarChar(1000)")]
		public string ISRemark
		{
			get
			{
				return this._ISRemark;
			}
			set
			{
				if ((this._ISRemark != value))
				{
					this.OnISRemarkChanging(value);
					this.SendPropertyChanging();
					this._ISRemark = value;
					this.SendPropertyChanged("ISRemark");
					this.OnISRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_OutStore")]
	public partial class tb_OutStore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _OSID;
		
		private string _StoreName;
		
		private string _GoodsName;
		
		private string _GoodsSpec;
		
		private string _GoodsUnit;
		
		private System.Nullable<long> _GoodsNum;
		
		private System.Nullable<decimal> _GoodsPrice;
		
		private System.Nullable<decimal> _GoodsAPrice;
		
		private System.Nullable<System.DateTime> _OSDate;
		
		private string _PGProvider;
		
		private string _PGPeople;
		
		private string _HandlePeople;
		
		private string _OSRemark;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOSIDChanging(long value);
    partial void OnOSIDChanged();
    partial void OnStoreNameChanging(string value);
    partial void OnStoreNameChanged();
    partial void OnGoodsNameChanging(string value);
    partial void OnGoodsNameChanged();
    partial void OnGoodsSpecChanging(string value);
    partial void OnGoodsSpecChanged();
    partial void OnGoodsUnitChanging(string value);
    partial void OnGoodsUnitChanged();
    partial void OnGoodsNumChanging(System.Nullable<long> value);
    partial void OnGoodsNumChanged();
    partial void OnGoodsPriceChanging(System.Nullable<decimal> value);
    partial void OnGoodsPriceChanged();
    partial void OnGoodsAPriceChanging(System.Nullable<decimal> value);
    partial void OnGoodsAPriceChanged();
    partial void OnOSDateChanging(System.Nullable<System.DateTime> value);
    partial void OnOSDateChanged();
    partial void OnPGProviderChanging(string value);
    partial void OnPGProviderChanged();
    partial void OnPGPeopleChanging(string value);
    partial void OnPGPeopleChanged();
    partial void OnHandlePeopleChanging(string value);
    partial void OnHandlePeopleChanged();
    partial void OnOSRemarkChanging(string value);
    partial void OnOSRemarkChanged();
    #endregion
		
		public tb_OutStore()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long OSID
		{
			get
			{
				return this._OSID;
			}
			set
			{
				if ((this._OSID != value))
				{
					this.OnOSIDChanging(value);
					this.SendPropertyChanging();
					this._OSID = value;
					this.SendPropertyChanged("OSID");
					this.OnOSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreName", DbType="VarChar(100)")]
		public string StoreName
		{
			get
			{
				return this._StoreName;
			}
			set
			{
				if ((this._StoreName != value))
				{
					this.OnStoreNameChanging(value);
					this.SendPropertyChanging();
					this._StoreName = value;
					this.SendPropertyChanged("StoreName");
					this.OnStoreNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsName", DbType="VarChar(50)")]
		public string GoodsName
		{
			get
			{
				return this._GoodsName;
			}
			set
			{
				if ((this._GoodsName != value))
				{
					this.OnGoodsNameChanging(value);
					this.SendPropertyChanging();
					this._GoodsName = value;
					this.SendPropertyChanged("GoodsName");
					this.OnGoodsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsSpec", DbType="VarChar(50)")]
		public string GoodsSpec
		{
			get
			{
				return this._GoodsSpec;
			}
			set
			{
				if ((this._GoodsSpec != value))
				{
					this.OnGoodsSpecChanging(value);
					this.SendPropertyChanging();
					this._GoodsSpec = value;
					this.SendPropertyChanged("GoodsSpec");
					this.OnGoodsSpecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsUnit", DbType="Char(8)")]
		public string GoodsUnit
		{
			get
			{
				return this._GoodsUnit;
			}
			set
			{
				if ((this._GoodsUnit != value))
				{
					this.OnGoodsUnitChanging(value);
					this.SendPropertyChanging();
					this._GoodsUnit = value;
					this.SendPropertyChanged("GoodsUnit");
					this.OnGoodsUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsNum", DbType="BigInt")]
		public System.Nullable<long> GoodsNum
		{
			get
			{
				return this._GoodsNum;
			}
			set
			{
				if ((this._GoodsNum != value))
				{
					this.OnGoodsNumChanging(value);
					this.SendPropertyChanging();
					this._GoodsNum = value;
					this.SendPropertyChanged("GoodsNum");
					this.OnGoodsNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsPrice", DbType="Money")]
		public System.Nullable<decimal> GoodsPrice
		{
			get
			{
				return this._GoodsPrice;
			}
			set
			{
				if ((this._GoodsPrice != value))
				{
					this.OnGoodsPriceChanging(value);
					this.SendPropertyChanging();
					this._GoodsPrice = value;
					this.SendPropertyChanged("GoodsPrice");
					this.OnGoodsPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsAPrice", AutoSync=AutoSync.Always, DbType="Money", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> GoodsAPrice
		{
			get
			{
				return this._GoodsAPrice;
			}
			set
			{
				if ((this._GoodsAPrice != value))
				{
					this.OnGoodsAPriceChanging(value);
					this.SendPropertyChanging();
					this._GoodsAPrice = value;
					this.SendPropertyChanged("GoodsAPrice");
					this.OnGoodsAPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> OSDate
		{
			get
			{
				return this._OSDate;
			}
			set
			{
				if ((this._OSDate != value))
				{
					this.OnOSDateChanging(value);
					this.SendPropertyChanging();
					this._OSDate = value;
					this.SendPropertyChanged("OSDate");
					this.OnOSDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGProvider", DbType="VarChar(100)")]
		public string PGProvider
		{
			get
			{
				return this._PGProvider;
			}
			set
			{
				if ((this._PGProvider != value))
				{
					this.OnPGProviderChanging(value);
					this.SendPropertyChanging();
					this._PGProvider = value;
					this.SendPropertyChanged("PGProvider");
					this.OnPGProviderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGPeople", DbType="VarChar(20)")]
		public string PGPeople
		{
			get
			{
				return this._PGPeople;
			}
			set
			{
				if ((this._PGPeople != value))
				{
					this.OnPGPeopleChanging(value);
					this.SendPropertyChanging();
					this._PGPeople = value;
					this.SendPropertyChanged("PGPeople");
					this.OnPGPeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HandlePeople", DbType="VarChar(20)")]
		public string HandlePeople
		{
			get
			{
				return this._HandlePeople;
			}
			set
			{
				if ((this._HandlePeople != value))
				{
					this.OnHandlePeopleChanging(value);
					this.SendPropertyChanging();
					this._HandlePeople = value;
					this.SendPropertyChanged("HandlePeople");
					this.OnHandlePeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSRemark", DbType="VarChar(1000)")]
		public string OSRemark
		{
			get
			{
				return this._OSRemark;
			}
			set
			{
				if ((this._OSRemark != value))
				{
					this.OnOSRemarkChanging(value);
					this.SendPropertyChanging();
					this._OSRemark = value;
					this.SendPropertyChanged("OSRemark");
					this.OnOSRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Provider")]
	public partial class tb_Provider : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PrID;
		
		private string _PrName;
		
		private string _PrPeople;
		
		private string _PrPhone;
		
		private string _PrFax;
		
		private string _PrRemark;
		
		private string _Editer;
		
		private System.Nullable<System.DateTime> _EditDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPrIDChanging(long value);
    partial void OnPrIDChanged();
    partial void OnPrNameChanging(string value);
    partial void OnPrNameChanged();
    partial void OnPrPeopleChanging(string value);
    partial void OnPrPeopleChanged();
    partial void OnPrPhoneChanging(string value);
    partial void OnPrPhoneChanged();
    partial void OnPrFaxChanging(string value);
    partial void OnPrFaxChanged();
    partial void OnPrRemarkChanging(string value);
    partial void OnPrRemarkChanged();
    partial void OnEditerChanging(string value);
    partial void OnEditerChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    #endregion
		
		public tb_Provider()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PrID
		{
			get
			{
				return this._PrID;
			}
			set
			{
				if ((this._PrID != value))
				{
					this.OnPrIDChanging(value);
					this.SendPropertyChanging();
					this._PrID = value;
					this.SendPropertyChanged("PrID");
					this.OnPrIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string PrName
		{
			get
			{
				return this._PrName;
			}
			set
			{
				if ((this._PrName != value))
				{
					this.OnPrNameChanging(value);
					this.SendPropertyChanging();
					this._PrName = value;
					this.SendPropertyChanged("PrName");
					this.OnPrNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrPeople", DbType="VarChar(20)")]
		public string PrPeople
		{
			get
			{
				return this._PrPeople;
			}
			set
			{
				if ((this._PrPeople != value))
				{
					this.OnPrPeopleChanging(value);
					this.SendPropertyChanging();
					this._PrPeople = value;
					this.SendPropertyChanged("PrPeople");
					this.OnPrPeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrPhone", DbType="VarChar(20)")]
		public string PrPhone
		{
			get
			{
				return this._PrPhone;
			}
			set
			{
				if ((this._PrPhone != value))
				{
					this.OnPrPhoneChanging(value);
					this.SendPropertyChanging();
					this._PrPhone = value;
					this.SendPropertyChanged("PrPhone");
					this.OnPrPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrFax", DbType="VarChar(20)")]
		public string PrFax
		{
			get
			{
				return this._PrFax;
			}
			set
			{
				if ((this._PrFax != value))
				{
					this.OnPrFaxChanging(value);
					this.SendPropertyChanging();
					this._PrFax = value;
					this.SendPropertyChanged("PrFax");
					this.OnPrFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrRemark", DbType="VarChar(1000)")]
		public string PrRemark
		{
			get
			{
				return this._PrRemark;
			}
			set
			{
				if ((this._PrRemark != value))
				{
					this.OnPrRemarkChanging(value);
					this.SendPropertyChanging();
					this._PrRemark = value;
					this.SendPropertyChanged("PrRemark");
					this.OnPrRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editer", DbType="VarChar(20)")]
		public string Editer
		{
			get
			{
				return this._Editer;
			}
			set
			{
				if ((this._Editer != value))
				{
					this.OnEditerChanging(value);
					this.SendPropertyChanging();
					this._Editer = value;
					this.SendPropertyChanged("Editer");
					this.OnEditerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_ReturnGoods")]
	public partial class tb_ReturnGood : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _RGID;
		
		private System.Nullable<long> _BGID;
		
		private string _StoreName;
		
		private string _GoodsName;
		
		private string _GoodsSpec;
		
		private System.Nullable<long> _RGNum;
		
		private System.Nullable<long> _NRGNum;
		
		private System.Nullable<System.DateTime> _RGDate;
		
		private string _HandlePeople;
		
		private string _RGPeople;
		
		private string _RGRemark;
		
		private string _Editer;
		
		private System.Nullable<System.DateTime> _EditDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRGIDChanging(long value);
    partial void OnRGIDChanged();
    partial void OnBGIDChanging(System.Nullable<long> value);
    partial void OnBGIDChanged();
    partial void OnStoreNameChanging(string value);
    partial void OnStoreNameChanged();
    partial void OnGoodsNameChanging(string value);
    partial void OnGoodsNameChanged();
    partial void OnGoodsSpecChanging(string value);
    partial void OnGoodsSpecChanged();
    partial void OnRGNumChanging(System.Nullable<long> value);
    partial void OnRGNumChanged();
    partial void OnNRGNumChanging(System.Nullable<long> value);
    partial void OnNRGNumChanged();
    partial void OnRGDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRGDateChanged();
    partial void OnHandlePeopleChanging(string value);
    partial void OnHandlePeopleChanged();
    partial void OnRGPeopleChanging(string value);
    partial void OnRGPeopleChanged();
    partial void OnRGRemarkChanging(string value);
    partial void OnRGRemarkChanged();
    partial void OnEditerChanging(string value);
    partial void OnEditerChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    #endregion
		
		public tb_ReturnGood()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RGID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long RGID
		{
			get
			{
				return this._RGID;
			}
			set
			{
				if ((this._RGID != value))
				{
					this.OnRGIDChanging(value);
					this.SendPropertyChanging();
					this._RGID = value;
					this.SendPropertyChanged("RGID");
					this.OnRGIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BGID", DbType="BigInt")]
		public System.Nullable<long> BGID
		{
			get
			{
				return this._BGID;
			}
			set
			{
				if ((this._BGID != value))
				{
					this.OnBGIDChanging(value);
					this.SendPropertyChanging();
					this._BGID = value;
					this.SendPropertyChanged("BGID");
					this.OnBGIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreName", DbType="VarChar(100)")]
		public string StoreName
		{
			get
			{
				return this._StoreName;
			}
			set
			{
				if ((this._StoreName != value))
				{
					this.OnStoreNameChanging(value);
					this.SendPropertyChanging();
					this._StoreName = value;
					this.SendPropertyChanged("StoreName");
					this.OnStoreNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsName", DbType="VarChar(50)")]
		public string GoodsName
		{
			get
			{
				return this._GoodsName;
			}
			set
			{
				if ((this._GoodsName != value))
				{
					this.OnGoodsNameChanging(value);
					this.SendPropertyChanging();
					this._GoodsName = value;
					this.SendPropertyChanged("GoodsName");
					this.OnGoodsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsSpec", DbType="VarChar(50)")]
		public string GoodsSpec
		{
			get
			{
				return this._GoodsSpec;
			}
			set
			{
				if ((this._GoodsSpec != value))
				{
					this.OnGoodsSpecChanging(value);
					this.SendPropertyChanging();
					this._GoodsSpec = value;
					this.SendPropertyChanged("GoodsSpec");
					this.OnGoodsSpecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RGNum", DbType="BigInt")]
		public System.Nullable<long> RGNum
		{
			get
			{
				return this._RGNum;
			}
			set
			{
				if ((this._RGNum != value))
				{
					this.OnRGNumChanging(value);
					this.SendPropertyChanging();
					this._RGNum = value;
					this.SendPropertyChanged("RGNum");
					this.OnRGNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRGNum", DbType="BigInt")]
		public System.Nullable<long> NRGNum
		{
			get
			{
				return this._NRGNum;
			}
			set
			{
				if ((this._NRGNum != value))
				{
					this.OnNRGNumChanging(value);
					this.SendPropertyChanging();
					this._NRGNum = value;
					this.SendPropertyChanged("NRGNum");
					this.OnNRGNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RGDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RGDate
		{
			get
			{
				return this._RGDate;
			}
			set
			{
				if ((this._RGDate != value))
				{
					this.OnRGDateChanging(value);
					this.SendPropertyChanging();
					this._RGDate = value;
					this.SendPropertyChanged("RGDate");
					this.OnRGDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HandlePeople", DbType="VarChar(20)")]
		public string HandlePeople
		{
			get
			{
				return this._HandlePeople;
			}
			set
			{
				if ((this._HandlePeople != value))
				{
					this.OnHandlePeopleChanging(value);
					this.SendPropertyChanging();
					this._HandlePeople = value;
					this.SendPropertyChanged("HandlePeople");
					this.OnHandlePeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RGPeople", DbType="VarChar(20)")]
		public string RGPeople
		{
			get
			{
				return this._RGPeople;
			}
			set
			{
				if ((this._RGPeople != value))
				{
					this.OnRGPeopleChanging(value);
					this.SendPropertyChanging();
					this._RGPeople = value;
					this.SendPropertyChanged("RGPeople");
					this.OnRGPeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RGRemark", DbType="VarChar(1000)")]
		public string RGRemark
		{
			get
			{
				return this._RGRemark;
			}
			set
			{
				if ((this._RGRemark != value))
				{
					this.OnRGRemarkChanging(value);
					this.SendPropertyChanging();
					this._RGRemark = value;
					this.SendPropertyChanged("RGRemark");
					this.OnRGRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editer", DbType="VarChar(20)")]
		public string Editer
		{
			get
			{
				return this._Editer;
			}
			set
			{
				if ((this._Editer != value))
				{
					this.OnEditerChanging(value);
					this.SendPropertyChanging();
					this._Editer = value;
					this.SendPropertyChanged("Editer");
					this.OnEditerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Storage")]
	public partial class tb_Storage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _StoreID;
		
		private string _StoreName;
		
		private string _StorePeople;
		
		private string _StorePhone;
		
		private string _StoreUnit;
		
		private System.Nullable<System.DateTime> _StoreDate;
		
		private string _StoreRemark;
		
		private string _Editer;
		
		private System.Nullable<System.DateTime> _EditDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStoreIDChanging(long value);
    partial void OnStoreIDChanged();
    partial void OnStoreNameChanging(string value);
    partial void OnStoreNameChanged();
    partial void OnStorePeopleChanging(string value);
    partial void OnStorePeopleChanged();
    partial void OnStorePhoneChanging(string value);
    partial void OnStorePhoneChanged();
    partial void OnStoreUnitChanging(string value);
    partial void OnStoreUnitChanged();
    partial void OnStoreDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStoreDateChanged();
    partial void OnStoreRemarkChanging(string value);
    partial void OnStoreRemarkChanged();
    partial void OnEditerChanging(string value);
    partial void OnEditerChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    #endregion
		
		public tb_Storage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long StoreID
		{
			get
			{
				return this._StoreID;
			}
			set
			{
				if ((this._StoreID != value))
				{
					this.OnStoreIDChanging(value);
					this.SendPropertyChanging();
					this._StoreID = value;
					this.SendPropertyChanged("StoreID");
					this.OnStoreIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreName", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StoreName
		{
			get
			{
				return this._StoreName;
			}
			set
			{
				if ((this._StoreName != value))
				{
					this.OnStoreNameChanging(value);
					this.SendPropertyChanging();
					this._StoreName = value;
					this.SendPropertyChanged("StoreName");
					this.OnStoreNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StorePeople", DbType="VarChar(20)")]
		public string StorePeople
		{
			get
			{
				return this._StorePeople;
			}
			set
			{
				if ((this._StorePeople != value))
				{
					this.OnStorePeopleChanging(value);
					this.SendPropertyChanging();
					this._StorePeople = value;
					this.SendPropertyChanged("StorePeople");
					this.OnStorePeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StorePhone", DbType="VarChar(20)")]
		public string StorePhone
		{
			get
			{
				return this._StorePhone;
			}
			set
			{
				if ((this._StorePhone != value))
				{
					this.OnStorePhoneChanging(value);
					this.SendPropertyChanging();
					this._StorePhone = value;
					this.SendPropertyChanged("StorePhone");
					this.OnStorePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreUnit", DbType="VarChar(100)")]
		public string StoreUnit
		{
			get
			{
				return this._StoreUnit;
			}
			set
			{
				if ((this._StoreUnit != value))
				{
					this.OnStoreUnitChanging(value);
					this.SendPropertyChanging();
					this._StoreUnit = value;
					this.SendPropertyChanged("StoreUnit");
					this.OnStoreUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StoreDate
		{
			get
			{
				return this._StoreDate;
			}
			set
			{
				if ((this._StoreDate != value))
				{
					this.OnStoreDateChanging(value);
					this.SendPropertyChanging();
					this._StoreDate = value;
					this.SendPropertyChanged("StoreDate");
					this.OnStoreDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreRemark", DbType="VarChar(1000)")]
		public string StoreRemark
		{
			get
			{
				return this._StoreRemark;
			}
			set
			{
				if ((this._StoreRemark != value))
				{
					this.OnStoreRemarkChanging(value);
					this.SendPropertyChanging();
					this._StoreRemark = value;
					this.SendPropertyChanged("StoreRemark");
					this.OnStoreRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editer", DbType="VarChar(20)")]
		public string Editer
		{
			get
			{
				return this._Editer;
			}
			set
			{
				if ((this._Editer != value))
				{
					this.OnEditerChanging(value);
					this.SendPropertyChanging();
					this._Editer = value;
					this.SendPropertyChanged("Editer");
					this.OnEditerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
